# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_snippet_snippethistory_snippetlibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippethistory',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
