# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_snippethistory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_snippets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
