# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_snippet_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippethistory',
            old_name='changed_by',
            new_name='created_by',
        ),
    ]
