# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161005_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='token',
            field=models.CharField(max_length=250),
        ),
    ]
